language: go
go:
  - tip
deploy:
  provider: heroku
  buildpack: https://github.com/heroku/heroku-buildpack-go.git
  api_key:
    secure: <your heroku api key encripted with travis encrypt>
  on: master 
